FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim-arm32v7 AS base
WORKDIR /app
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["HydroPi.csproj", "./"]
RUN dotnet restore "HydroPi.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "HydroPi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "HydroPi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "HydroPi.dll"]
